// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/images/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新图片的描述、可见性等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "更新图片信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateImageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片更新成功相应",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除指定ID的图片及其关联数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "删除图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片删除成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.ImageDeleteResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/images/{id}/tags": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "给图片添加一个或多个标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "给图片添加标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "标签列表",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddTagsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加标签成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.ImageTagResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/images/{id}/tags/{tag_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从图片中移除指定标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "从图片中移除标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标签ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "移除标签成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.ImageTagResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "get": {
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/tags": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new tag in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Create a new tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer user token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Tag to create",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTagReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created tag",
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                }
            }
        },
        "/api/auth/tags/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing tag's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Update a tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer user token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated tag information",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTagReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated tag",
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a tag and remove it from all associated images",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Delete a tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer user token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tag deletion response",
                        "schema": {
                            "$ref": "#/definitions/response.TagDeleteResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传新图片并可选添加描述、主标签等信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "是否公开",
                        "name": "is_public",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "主标签",
                        "name": "main_tag",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传图片成功响应",
                        "schema": {
                            "$ref": "#/definitions/response.ImageUploadResponse"
                        }
                    }
                }
            }
        },
        "/api/private/setting": {
            "get": {
                "description": "获取设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "获取设置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keys",
                        "name": "keys",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "保存设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "保存设置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设置",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SettingItem"
                            }
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "删除设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "删除设置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/private/setting/token": {
            "post": {
                "description": "重置token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "重置token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/private/settings": {
            "get": {
                "description": "列出设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "列出设置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "groups",
                        "name": "groups",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SettingItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/private/users": {
            "post": {
                "description": "列出用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "列出用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分类信息",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.PageResp"
                        }
                    }
                }
            }
        },
        "/api/public/images": {
            "post": {
                "description": "分页获取所有图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "分页列出图片",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片列表和总数",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PageResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "$ref": "#/definitions/model.Image"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/public/images/count": {
            "get": {
                "description": "获取系统中的图片总数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取图片数量",
                "responses": {
                    "200": {
                        "description": "图片数量",
                        "schema": {
                            "$ref": "#/definitions/response.ImageCountResponse"
                        }
                    }
                }
            }
        },
        "/api/public/images/tag": {
            "post": {
                "description": "获取包含特定标签的所有图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "根据标签获取图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "分页参数",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片列表和总数",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PageResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "$ref": "#/definitions/model.Image"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/public/images/{id}": {
            "get": {
                "description": "根据ID获取图片详细信息，包括标签等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "根据ID获取图片",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "图片ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片信息",
                        "schema": {
                            "$ref": "#/definitions/model.Image"
                        }
                    }
                }
            }
        },
        "/api/public/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handles.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/handles.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/public/settings": {
            "get": {
                "description": "获取公共设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "获取公共设置",
                "responses": {
                    "200": {
                        "description": "公共设置",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/public/tags": {
            "post": {
                "description": "Get a paginated list of all tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "List tags",
                "parameters": [
                    {
                        "description": "Pagination parameters",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tags list and count",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PageResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Tag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/public/tags/image/{image_id}": {
            "get": {
                "description": "Get all tags associated with a specific image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Get tags for image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Image ID",
                        "name": "image_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of tags",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tag"
                            }
                        }
                    }
                }
            }
        },
        "/api/public/tags/name": {
            "get": {
                "description": "Get tag details by its name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Get tag by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tag details",
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                }
            }
        },
        "/api/public/tags/popular": {
            "get": {
                "description": "Get the most popular tags by usage count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Get popular tags",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Maximum number of tags to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of popular tags",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tag"
                            }
                        }
                    }
                }
            }
        },
        "/api/public/tags/search": {
            "get": {
                "description": "Search for tags that start with the given prefix",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Search tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag prefix to search for",
                        "name": "prefix",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of matching tags",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tag"
                            }
                        }
                    }
                }
            }
        },
        "/api/public/tags/{id}": {
            "get": {
                "description": "Get tag details by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "Get tag by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tag details",
                        "schema": {
                            "$ref": "#/definitions/model.Tag"
                        }
                    }
                }
            }
        },
        "/images/image/random": {
            "get": {
                "description": "随机获取一个图片，支持按分类过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "image"
                ],
                "summary": "随机获取一个图片",
                "responses": {
                    "200": {
                        "description": "图片内容",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/images/image/{name}": {
            "get": {
                "description": "直接返回图片文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "image"
                ],
                "summary": "根据文件名获取图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图片内容",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/images/thumbnail/{name}": {
            "get": {
                "description": "根据文件名获取图片的缩略图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/*"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取图片缩略图",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "缩略图内容",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.PageResp": {
            "type": "object",
            "properties": {
                "content": {},
                "total": {
                    "type": "integer"
                }
            }
        },
        "handles.LoginReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handles.LoginResp": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.Image": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "download_count": {
                    "description": "下载次数",
                    "type": "integer"
                },
                "file_name": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "original_name": {
                    "type": "string"
                },
                "path": {
                    "description": "图片路径",
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "tags": {
                    "description": "标签，多对多关系",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                },
                "thumbnail_path": {
                    "description": "缩略图路径",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "view_count": {
                    "description": "浏览次数",
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.PageReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                }
            }
        },
        "model.SettingItem": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "flag": {
                    "description": "0 = public, 1 = private, 2 = readonly, 3 = deprecated, etc.",
                    "type": "integer"
                },
                "group": {
                    "description": "use to group setting in frontend",
                    "type": "integer"
                },
                "help": {
                    "description": "help message",
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "key": {
                    "description": "unique key",
                    "type": "string"
                },
                "options": {
                    "description": "values for select",
                    "type": "string"
                },
                "type": {
                    "description": "string, number, bool, select",
                    "type": "string"
                },
                "value": {
                    "description": "value",
                    "type": "string"
                }
            }
        },
        "model.Tag": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "使用此标签的图片数量",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "标签名称，唯一且索引",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "request.AddTagsReq": {
            "type": "object",
            "required": [
                "tags"
            ],
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.CreateTagReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "request.UpdateImageReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "main_tag": {
                    "type": "string"
                }
            }
        },
        "response.ImageCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "response.ImageDeleteResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "Image deleted successfully"
                }
            }
        },
        "response.ImageTagResponse": {
            "type": "object",
            "properties": {
                "image_id": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "response.ImageUploadResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "path": {
                    "type": "string",
                    "example": "abc123.jpg"
                }
            }
        },
        "response.TagDeleteResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
